// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyXmnrLv-bwQN8ezlPS-4oh7FTB21lvRk',
    appId: '1:373334886770:web:44dec10c935e6c50d675eb',
    messagingSenderId: '373334886770',
    projectId: 'x-manage-device',
    authDomain: 'x-manage-device.firebaseapp.com',
    storageBucket: 'x-manage-device.appspot.com',
    measurementId: 'G-GS8T19K59M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVbgMu0LK5Fgj2tpkh-gWBB8DQc7v_K_E',
    appId: '1:373334886770:android:e071d707aeb058d7d675eb',
    messagingSenderId: '373334886770',
    projectId: 'x-manage-device',
    storageBucket: 'x-manage-device.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqJbHoOLa3Yl-pdQKDcadSPW_Ic7v28s0',
    appId: '1:373334886770:ios:5cc485d02b104a33d675eb',
    messagingSenderId: '373334886770',
    projectId: 'x-manage-device',
    storageBucket: 'x-manage-device.appspot.com',
    iosBundleId: 'com.example.xstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqJbHoOLa3Yl-pdQKDcadSPW_Ic7v28s0',
    appId: '1:373334886770:ios:5cc485d02b104a33d675eb',
    messagingSenderId: '373334886770',
    projectId: 'x-manage-device',
    storageBucket: 'x-manage-device.appspot.com',
    iosBundleId: 'com.example.xstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyXmnrLv-bwQN8ezlPS-4oh7FTB21lvRk',
    appId: '1:373334886770:web:9f20448f7432dd8fd675eb',
    messagingSenderId: '373334886770',
    projectId: 'x-manage-device',
    authDomain: 'x-manage-device.firebaseapp.com',
    storageBucket: 'x-manage-device.appspot.com',
    measurementId: 'G-7R8ZYVNE3D',
  );

}